"""Add AI decision fields

Revision ID: 14d0f38e8b1e
Revises: 0ad9535d1032
Create Date: 2026-07-21 11:59:36.819470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14d0f38e8b1e'
down_revision: Union[str, Sequence[str], None] = '0ad9535d1032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_applications', sa.Column('eligibility_score', sa.Integer(), nullable=True))
    op.add_column('loan_applications', sa.Column('recommendation', sa.String(), nullable=True))
    op.add_column('loan_applications', sa.Column('risk_level', sa.String(), nullable=True))
    op.add_column('loan_applications', sa.Column('ai_confidence', sa.Integer(), nullable=True))
    op.add_column('loan_applications', sa.Column('verification_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan_applications', 'verification_status')
    op.drop_column('loan_applications', 'ai_confidence')
    op.drop_column('loan_applications', 'risk_level')
    op.drop_column('loan_applications', 'recommendation')
    op.drop_column('loan_applications', 'eligibility_score')
    # ### end Alembic commands ###
