"""Add officer review fields

Revision ID: f3976e6c3abf
Revises: 14d0f38e8b1e
Create Date: 2026-07-22 09:03:45.438905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3976e6c3abf'
down_revision: Union[str, Sequence[str], None] = '14d0f38e8b1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_applications', sa.Column('officer_decision', sa.String(), nullable=True))
    op.add_column('loan_applications', sa.Column('officer_comment', sa.String(), nullable=True))
    op.add_column('loan_applications', sa.Column('reviewed_by', sa.String(), nullable=True))
    op.add_column('loan_applications', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan_applications', 'reviewed_at')
    op.drop_column('loan_applications', 'reviewed_by')
    op.drop_column('loan_applications', 'officer_comment')
    op.drop_column('loan_applications', 'officer_decision')
    # ### end Alembic commands ###
